#pragma once


//				[NETWORK_MESSAGE]
#define MESSAGE_NETWORK_LOGINCHAR						1
#define MESSAGE_NETWORK_LOGINCHAR_LOGIN						1
#define MESSAGE_NETWORK_LOGINCHAR_WORLDLIST					2
#define MESSAGE_NETWORK_LOGINCHAR_MOVEZONESERVER			3
#define MESSAGE_NETWORK_LOGINCHAR_CHARLIST					4
#define MESSAGE_NETWORK_LOGINCHAR_CHARCREATE				5
#define MESSAGE_NETWORK_LOGINCHAR_CHARREMOVE				6
#define MESSAGE_NETWORK_LOGINCHAR_ZONECONNECT				7
#define MESSAGE_NETWORK_LOGINCHAR_EXITZONESERVER			8
#define MESSAGE_NETWORK_LOGINCHAR_CHARLOGOUT				9
#define MESSAGE_NETWORK_LOGINCHAR_OTHERCHARLOGOUT			10
#define MESSAGE_NETWORK_LOGINCHAR_OTHERCHARLOGOUTNOTIFY		11

#define MESSAGE_NETWORK_INIT						2
#define MESSAGE_NETWORK_INIT_CHAR							1
#define MESSAGE_NETWORK_INIT_INVENTORY						2
#define MESSAGE_NETWORK_INIT_NPCINVENTORY					3
#define MESSAGE_NETWORK_INIT_SKILL							4
#define MESSAGE_NETWORK_INIT_GUILD							5
#define MESSAGE_NETWORK_INIT_ADDRESSBOOK					6
#define MESSAGE_NETWORK_INIT_QUEST							7
#define MESSAGE_NETWORK_INIT_CHARHISTORY					8
#define MESSAGE_NETWORK_INIT_EQUIPMENT						9
#define MESSAGE_NETWORK_INIT_MONSTERNPC						10
#define MESSAGE_NETWORK_INIT_OTHERCHAR						11
#define MESSAGE_NETWORK_INIT_ITEM							12
#define MESSAGE_NETWORK_INIT_INTIREGENCHAR					13
#define MESSAGE_NETWORK_INIT_GUILDINVENTORY					14

#define MESSAGE_NETWORK_MOVE						3
#define MESSAGE_NETWORK_MOVE_CHARMOVE						1
#define MESSAGE_NETWORK_MOVE_OTHERCHARMOVE					2
#define MESSAGE_NETWORK_MOVE_ITEMMOVE						3
#define MESSAGE_NETWORK_MOVE_MAPITEMAPPEAR					4
#define MESSAGE_NETWORK_MOVE_MAPITEMDISAPPEAR				5
#define MESSAGE_NETWORK_MOVE_MONSTERMOVESTEOP				6
#define MESSAGE_NETWORK_MOVE_MONSTERMOVENSTEP				7
#define MESSAGE_NETWORK_MOVE_MONSTERMOVEEND					8
#define MESSAGE_NETWORK_MOVE_CHARRECALL						9
#define MESSAGE_NETWORK_MOVE_RECALLNOTIFY					10
#define MESSAGE_NETWORK_MOVE_RECALLRESULT					11
#define MESSAGE_NETWORK_MOVE_RECALLRESULTNOTIRY				12
#define MESSAGE_NETWORK_MOVE_ITEMPACKING					13
#define MESSAGE_NETWORK_MOVE_ITEMUNPACKING					14
#define MESSAGE_NETWORK_MOVE_ITEMUSE						15
#define MESSAGE_NETWORK_MOVE_ITEMUSEBROADCAST				16
#define MESSAGE_NETWORK_MOVE_MOVEPORTAL						17
#define MESSAGE_NETWORK_MOVE_ATKCHAR						18
#define MESSAGE_NETWORK_MOVE_ATKCHARBROADCAST				19

#define MESSAGE_NETWORK_EQUIP							4
#define MESSAGE_NETWORK_EQUIP_ITEMEQUIP						1
#define MESSAGE_NETWORK_EQUIP_ITEMEQUIPBROADCAST			2
#define MESSAGE_NETWORK_EQUIP_ITEMABRASION					3
#define MESSAGE_NETWORK_EQUIP_ITEMABRASIONBROADCAST			4
#define MESSAGE_NETWORK_EQUIP_ITEMDURABILITYDECREASE		5

#define MESSAGE_NETWORK_CHAT							5
#define MESSAGE_NETWORK_CHAT_REQNORMALCHAT					1
#define MESSAGE_NETWORK_CHAT_NORMALCHAT						2
#define MESSAGE_NETWORK_CHAT_REQWHISPERCHAT					3
#define MESSAGE_NETWORK_CHAT_WHISPERCHAT					4
#define MESSAGE_NETWORK_CHAT_REQSHOUTCHAT					5
#define MESSAGE_NETWORK_CHAT_SHOUTCHAT						6
#define MESSAGE_NETWORK_CHAT_REQPARTYCHAT					7
#define MESSAGE_NETWORK_CHAT_PARTYCHAT						8
#define MESSAGE_NETWORK_CHAT_REQGUILDCHAT					9
#define MESSAGE_NETWORK_CHAT_GUILDCHAT						10
#define MESSAGE_NETWORK_CHAT_REQNOTIFYMESSAGE				11
#define MESSAGE_NETWORK_CHAT_NOTIFYMESSAGE					12

#define MESSAGE_NETWORK_PARTY							6
#define MESSAGE_NETWORK_PARTY_CREATEPARTY					1
#define MESSAGE_NETWORK_PARTY_DISBANDPARTY					2
#define MESSAGE_NETWORK_PARTY_DISBANDPARTYBROADCAST			3
#define MESSAGE_NETWORK_PARTY_JOINPARTY						4
#define MESSAGE_NETWORK_PARTY_JOINPARTYNOTIRY				5
#define MESSAGE_NETWORK_PARTY_JOINPARTYRESULT				6
#define MESSAGE_NETWORK_PARTY_JOINPARTYRESULTNOTIFY			7
#define MESSAGE_NETWORK_PARTY_NEWPARTYMEMBER				8
#define MESSAGE_NETWORK_PARTY_SECEDEPARTY					9
#define MESSAGE_NETWORK_PARTY_SECEDEPARTYBROADCAST			10
#define MESSAGE_NETWORK_PARTY_PARTYLIST						11
#define MESSAGE_NETWORK_PARTY_CREATEGUILD					12
#define MESSAGE_NETWORK_PARTY_DISBANDGUILD					13
#define MESSAGE_NETWORK_PARTY_CREATEGUILDBROADCAST			14
#define MESSAGE_NETWORK_PARTY_DISBANDGUILDBROADCAST			15
#define MESSAGE_NETWORK_PARTY_JOINGUILD						16
#define MESSAGE_NETWORK_PARTY_JOINGUILDNOTIFY				17
#define MESSAGE_NETWORK_PARTY_JOINGUILDRESULT				18
#define MESSAGE_NETWORK_PARTY_JOINGUILDRESULT_NOTIFY		19
#define MESSAGE_NETWORK_PARTY_NEW_GUILD_MEMBER				20
#define MESSAGE_NETWORK_PARTY_SECEDE_GUILD					21
#define MESSAGE_NETWORK_PARTY_SECEDE_GUILD_BROADCAST		22
#define MESSAGE_NETWORK_PARTY_JOINADDBOOK					23
#define MESSAGE_NETWORK_PARTY_JOINADDBOOKNOTIFY				24
#define MESSAGE_NETWORK_PARTY_JOINADDBOOKRESULT				25
#define MESSAGE_NETWORK_PARTY_JOINADDBOOKRESULTNOTIFY		26
#define MESSAGE_NETWORK_PARTY_ADDBOOKMEMBERDELETE			27
#define MESSAGE_NETWORK_PARTY_ADDBOOKLOGINNOTIFY			28

#define MESSAGE_NETWORK_QUEST							7

#define MESSAGE_NETWORK_STATUS							8
#define MESSAGE_NETWORK_STATUS_MONSTERDISAPPEAR				1
#define MESSAGE_NETWORK_STATUS_CHARSTATUS					2
#define MESSAGE_NETWORK_STATUS_MONSTERSTATUSBROADCAST		3
#define MESSAGE_NETWORK_STATUS_CHARDEATH					4
#define MESSAGE_NETWORK_STATUS_CHARMONSTERDEATHBROADCAST	5
#define MESSAGE_NETWORK_STATUS_CHARHPRECOVERY				6
#define MESSAGE_NETWORK_STATUS_MONSTERHPRECOVERY			7
#define MESSAGE_NETWORK_STATUS_CHARCASTPROMOTE				8
#define MESSAGE_NETWORK_STATUS_CHARCASTPROMOTEBROADCAST		9
#define MESSAGE_NETWORK_STATUS_CHAR_PING					10

#define MESSAGE_NETWORK_PARA							9
#define MESSAGE_NETWORK_PARA_CHAR_PARAMS					1
#define MESSAGE_NETWORK_PARA_ITEM_PARAMS					2
#define MESSAGE_NETWORK_PARA_MONSTER_PARAMS					3
#define MESSAGE_NETWORK_PARA_CHAR_PARAMS_CHANGE				4
#define MESSAGE_NETWORK_PARA_MONSTER_PARAMS_CHANGE			5
#define MESSAGE_NETWORK_PARA_ITEM_PARAMS_CHANGE				6
#define MESSAGE_NETWORK_PARA_CHAKRA_RISING					7
#define MESSAGE_NETWORK_PARA_BRAHMAN_RISING					8
#define MESSAGE_NETWORK_PARA_INCREASE_INVENTORY_SLOT		9
#define MESSAGE_NETWORK_PARA_NPC_POINT_UP					10

#define MESSAGE_NETWORK_SKILL							10
#define MESSAGE_NETWORK_SKILL_REQQSKILLREGIST				1
#define MESSAGE_NETWORK_SKILL_SKILLREGIST					2
#define MESSAGE_NETWORK_SKILL_SKILLSELECT					3
#define MESSAGE_NETWORK_SKILL_SKILLUSE2CHAR					4
#define MESSAGE_NETWORK_SKILL_SKILLREADYCHARBROADCAST		5
#define MESSAGE_NETWORK_SKILL_SKILL_ATK_CHAR				6
#define MESSAGE_NETWORK_SKILL_SKILL_ATK_CHAR_BROADCAST		7
#define MESSAGE_NETWORK_SKILL_SKILL_LEVEL_UP				8
#define MESSAGE_NETWORK_SKILL_SHOP_SKILL_LIST				9

#define MESSAGE_NETWORK_ITEMECO							11
#define MESSAGE_NETWORK_ITEMECO_SHOP_ITEM_LIST				1
#define MESSAGE_NETWORK_ITEMECO_ITEM_MAKING					2
#define MESSAGE_NETWORK_ITEMECO_ITEM_REDEEM					3
#define MESSAGE_NETWORK_ITEMECO_ITEM_REPAIR					4
#define MESSAGE_NETWORK_ITEMECO_ITEM_DISMANTLE				5
#define MESSAGE_NETWORK_ITEMECO_ITEM_CONTRIBUTION			6
#define MESSAGE_NETWORK_ITEMECO_PRANA_CONTRIBUTION			7

#define MESSAGE_NETWORK_EXCHANGE						12
#define MESSAGE_NETWORK_EXCHANGE_EXCHANGE					1
#define MESSAGE_NETWORK_EXCHANGE_EXCHANGE_NOTIFY			2
#define MESSAGE_NETWORK_EXCHANGE_EXCHANGE_RESULT			3
#define MESSAGE_NETWORK_EXCHANGE_EXCHANGE_RESULT_NOTIFY		4
#define MESSAGE_NETWORK_EXCHANGE_EXCHANGE_ADD				5
#define MESSAGE_NETWORK_EXCHANGE_EXCHANGE_ADD_NOTIFY		6
#define MESSAGE_NETWORK_EXCHANGE_EXCHANGE_ERASE				7
#define MESSAGE_NETWORK_EXCHANGE_EXCHANGE_ERASE_NOTIFY		8
#define MESSAGE_NETWORK_EXCHANGE_EXCHANGE_ACCEPT			9
#define MESSAGE_NETWORK_EXCHANGE_EXCHANGE_ACCEPT_NOTIFY		10
#define MESSAGE_NETWORK_EXCHANGE_EXCHANGE_CANCEL			11
#define MESSAGE_NETWORK_EXCHANGE_EXCHANGE_MONEY				12
#define MESSAGE_NETWORK_EXCHANGE_EXCHANGE_MONEY_RESULT		13
#define MESSAGE_NETWORK_EXCHANGE_EXCHANGE_MONEY_NOTIFY		14

#define MESSAGE_NETWORK_EVENT							13
#define MESSAGE_NETWORK_EVENT_EVENT_OCCURRENCE				1
#define MESSAGE_NETWORK_EVENT_EVENT_OCCURRENCE_BROADCAST1	2
#define MESSAGE_NETWORK_EVENT_EVENT_EXTINCT_BROADCAST		3


class HTInfoLoad
{
public:
	HTInfoLoad(void);
	~HTInfoLoad(void);

	//---------네트워크 메시지 히스토리 창으로 셋팅----------//
	HTvoid						HT_vNetWorkMessageSetHistory( HTint, CHTString );
	HTvoid						HT_vNetWorkMessageSetHistory( HTint, CHTString, HT_COLOR, HT_COLOR );
};
